name: CI EventKit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  ci:
    uses: weekendsuperhero-io/platform-tools/.github/workflows/reusable-rust-ci.yml@main
    with:
      check-os-json: '["macos-26"]'
      rust-cache-provider: github
      docs-os: macos-26
      build-matrix-json: >-
        [
          {"os":"macos-26","target":"x86_64-apple-darwin"},
          {"os":"macos-26","target":"aarch64-apple-darwin"ß}
        ]
    secrets: inherit
